openapi: 3.0.0
info:
  title: Availability Config API
  version: v0
  description: |
    Use this API when ATP information needs to be retrieved from an external
    [order management system](/docs/glossary.html#term-OMS).
servers:
  - url: 'https://dodici.x.newstore.net/v0'
components:
  securitySchemes:
    newStoreAccessToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - newStoreAccessToken: []
paths:
  /config/availability/webhook:
    get:
      responses:
        '200':
          description: Webhook Configuration Setting.
          content:
            application/json:
              example:
                url: 'https://lambda.com/'
                api_key: 962b5dfbc57da5448cb4
                external_identifier: product_id
                timeout: 15
              schema:
                description: The webhook configuration.
                type: object
                required:
                  - url
                  - api_key
                  - external_identifier
                  - timeout
                properties:
                  url:
                    type: string
                    format: uri
                    minLength: 1
                    description: Describes the URL being called from the platform.
                  api_key:
                    type: string
                    minLength: 20
                    description: Describes API key used for authenticating requests.
                  external_identifier:
                    type: string
                    minLength: 1
                    description: Describes identifier being used by an integration to look up ATP information in an external system. Currently only 'product_id' is supported.
                  timeout:
                    type: integer
                    minimum: 5
                    maximum: 60
                    description: Defines the timeout for HTTP requests.
        '204':
          description: No configuration found.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              example:
                error_code: internal_server_error
                message: The request didn't succeed.
                request_id: ec2f3c9bb016ba971bf6074098363
              schema:
                description: The error response.
                type: object
                required:
                  - error_code
                  - message
                  - request_id
                properties:
                  error_code:
                    type: string
                    minLength: 1
                    description: The specific code of the error.
                  message:
                    type: string
                    minLength: 1
                    description: A message explaining the error.
                  request_id:
                    type: string
                    minLength: 1
                    description: 'The identifier of the request, which can be used for tracing.'
      description: |
        Retrieves the current configuration for requesting ATP information from the external
        order management system.
      summary: Get webhook configuration
      operationId: get-webhook-configuration
    put:
      responses:
        '200':
          description: Webhook Configuration Setting.
          content:
            application/json:
              example:
                url: 'https://lambda.com/'
                api_key: 962b5dfbc57da5448cb4
                external_identifier: product_id
                timeout: 15
              schema:
                description: The webhook configuration.
                type: object
                required:
                  - url
                  - api_key
                  - external_identifier
                  - timeout
                properties:
                  url:
                    type: string
                    format: uri
                    minLength: 1
                    description: Describes the URL being called from the platform.
                  api_key:
                    type: string
                    minLength: 20
                    description: Describes API key used for authenticating requests.
                  external_identifier:
                    type: string
                    minLength: 1
                    description: Describes identifier being used by an integration to look up ATP information in an external system. Currently only 'product_id' is supported.
                  timeout:
                    type: integer
                    minimum: 5
                    maximum: 60
                    description: Defines the timeout for HTTP requests.
        '400':
          description: Bad Request Error.
          content:
            application/json:
              example:
                error_code: bad_request
                message: Please provide a URL.
                request_id: ec2f3c9bb016ba971bf6074098363
              schema:
                description: The error response.
                type: object
                required:
                  - error_code
                  - message
                  - request_id
                properties:
                  error_code:
                    type: string
                    minLength: 1
                    description: The specific code of the error.
                  message:
                    type: string
                    minLength: 1
                    description: A message explaining the error.
                  request_id:
                    type: string
                    minLength: 1
                    description: 'The identifier of the request, which can be used for tracing.'
        '409':
          description: Conflict Error.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              example:
                error_code: internal_server_error
                message: The request didn't succeed.
                request_id: ec2f3c9bb016ba971bf6074098363
              schema:
                description: The error response.
                type: object
                required:
                  - error_code
                  - message
                  - request_id
                properties:
                  error_code:
                    type: string
                    minLength: 1
                    description: The specific code of the error.
                  message:
                    type: string
                    minLength: 1
                    description: A message explaining the error.
                  request_id:
                    type: string
                    minLength: 1
                    description: 'The identifier of the request, which can be used for tracing.'
      description: |
        Specify that the retailer will use an external
        order management system for using ATP information.

        If you want to disable using ATP information from the external OMS, please delete the configuration.
      summary: Update webhook configuration
      operationId: update-webhook-configuration
      requestBody:
        content:
          application/json:
            example:
              url: 'https://lambda.com/'
              api_key: 962b5dfbc57da5448cb4
              external_identifier: product_id
              timeout: 15
            schema:
              description: The webhook configuration.
              type: object
              required:
                - url
                - api_key
                - external_identifier
                - timeout
              properties:
                url:
                  type: string
                  format: uri
                  minLength: 1
                  description: Describes the URL being called from the platform.
                api_key:
                  type: string
                  minLength: 20
                  description: Describes API key used for authenticating requests.
                external_identifier:
                  type: string
                  minLength: 1
                  description: Describes identifier being used by an integration to look up ATP information in an external system. Currently only 'product_id' is supported.
                timeout:
                  type: integer
                  minimum: 5
                  maximum: 60
                  description: Defines the timeout for HTTP requests.
        required: true
    delete:
      responses:
        '200':
          description: Successfully deleted.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              example:
                error_code: internal_server_error
                message: The request didn't succeed.
                request_id: ec2f3c9bb016ba971bf6074098363
              schema:
                description: The error response.
                type: object
                required:
                  - error_code
                  - message
                  - request_id
                properties:
                  error_code:
                    type: string
                    minLength: 1
                    description: The specific code of the error.
                  message:
                    type: string
                    minLength: 1
                    description: A message explaining the error.
                  request_id:
                    type: string
                    minLength: 1
                    description: 'The identifier of the request, which can be used for tracing.'
      description: |
        Deletes the current configuration for requesting ATP information from the external
        order management system.
      summary: Delete webhook configuration
      operationId: delete-webhook-configuration

